version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "(%(name)s) %(levelname)s: %(message)s"

  training:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  training_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: fgvc_train.log
    encoding: utf8

loggers:
  fgvc:
    level: DEBUG
    handlers: [ console ]
    propagate: no

  fgvc-training:
    level: INFO
    handlers: [ console, training_file_handler ]
    propagate: no

root:
  level: INFO
  handlers: [ console ]
  propagate: no
