[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
# skip-string-normalization = true  # requouting '...' -> "..." can be disabled

[tool.isort]
line_length = 100
profile = "black"
